pointcloud_filter_node:
  ros__parameters:
    input_topic: "/livox/lidar/pointcloud"
    output_topic: "/filtered_points"
    distance_threshold: 0.2
    max_distance: 200.0
    angle_filters: [-3.3, -2.1, 2.1, 3.3]
    robot_min_x: -0.0
    robot_max_x: 0.0  #0.52
    robot_min_y: -0.0 #0.51
    robot_max_y: 0.0  #0.51
#0.01씩-
    # Ground filtering parameters
    ground_ignore_radius: 7.0          # Beyond this distance, ground points will be ignored
    ground_height_threshold: -0.5       # Points below this height are considered ground
